name: ferry_exec
version: 0.3.0-dev.5
homepage: https://ferrygraphql.com/
description: A strongly typed execution interface for GraphQL operations
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql: '>=0.14.0 <2.0.0'
  gql_exec: '>=0.4.0 <2.0.0'
  gql_link: '>=0.5.0 <2.0.0'
  meta: ^1.3.0
  async: ^2.5.0
  collection: ^1.15.0
  built_collection: ^5.1.1
  built_value: ^8.1.2
dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
  build_runner: ^2.1.1
  built_value_generator: ^8.1.1
