name: ferry_hive_ce_store
version: 0.0.1
homepage: https://ferry.gql-dart.dev
description: Hive-based Store implementation for Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'
topics:
  - graphql
  - gql
  - ferry
  - hive
dependencies:
  hive_ce: ^2.0.0
  ferry_store: ^0.6.1
  rxdart: ^0.28.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.8
  lints: ^5.0.0
