name: pokemon_explorer
version: 0.0.3-dev.4
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql_link: '>=0.5.0 <2.0.0'
  gql_http_link: '>=0.4.0 <2.0.0'
  ferry: ^0.15.0-dev.6
  ferry_hive_store: ^0.5.2-dev.1
  ferry_flutter: ^0.9.0-dev.6
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  get_it: ^7.1.3
  path_provider: ^2.0.0
  flutter:
    sdk: flutter
  built_collection: ^5.0.0
  collection: ^1.15.0
dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: ^2.0.2
  ferry_generator: ^0.9.0
  flutter_test:
    sdk: flutter
  gql_exec: ^1.0.0
flutter:
  uses-material-design: true
