name: pokemon_explorer
version: 0.0.3
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql_link: ^0.4.0-nullsafety.3
  gql_http_link: ^0.4.0-nullsafety.1
  ferry: ^0.10.1-0.1.nullsafety.0
  ferry_hive_store: ^0.4.4
  ferry_flutter: ^0.5.4
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  get_it: ^7.1.3
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.0.2
  ferry_generator: ^0.5.0-dev.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
