name: pokemon_explorer
version: 0.0.1
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  gql_link: ^0.3.0
  gql_http_link: ^0.2.9
  ferry: ^0.7.0
  ferry_generator: ^0.2.1
  ferry_hive_store: ^0.2.2
  ferry_flutter: ^0.2.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  get_it: ^4.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^1.10.1
  gql_build: ^0.1.2
  gql_code_builder: ^0.1.2
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
