name: pokemon_explorer
version: 0.0.3-dev.4
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql_link: ^0.5.0
  gql_http_link: ^0.4.0
  ferry: ^0.11.0
  ferry_hive_store: ^0.4.5
  ferry_flutter: ^0.6.1+1
  hive: ^2.0.0
  get_it: ^7.1.3
  path_provider: ^2.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: ^2.0.2
  ferry_generator: ^0.6.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
