name: pokemon_explorer
version: 0.0.3-dev.4
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql_link: ^0.5.0
  gql_http_link: ^0.4.0
  ferry: ^0.14.0-dev.7
  ferry_hive_store: ^0.5.1-dev.3
  ferry_flutter: ^0.8.0-dev.11
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  get_it: ^7.1.3
  path_provider: ^2.0.0
  flutter:
    sdk: flutter
  built_collection: ^5.0.0
  collection: ^1.15.0
dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: ^2.0.2
  ferry_generator: ^0.8.0-dev.2
  flutter_test:
    sdk: flutter
  gql_exec: ^0.4.4
flutter:
  uses-material-design: true
