name: ferry_generator
version: 0.14.0-dev.0
homepage: https://ferry.gql-dart.dev
description: Generated types for Ferry GraphQL Client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'
topics:
  - graphql
  - gql
  - ferry
  - codegen
dependencies:
  gql: '>=0.14.0 <2.0.0'
  gql_code_builder: ^0.14.0
  gql_code_builder_serializers: ^0.1.0
  gql_tristate_value: ^1.0.0
  built_collection: ^5.0.0
  code_builder: ^4.3.0
  build: ^2.0.0
  path: ^1.8.0
  ferry_exec: ^0.8.0-dev.0
  yaml: ^3.1.0
  dart_style: ^3.0.1
  pub_semver: ^2.0.0
  glob: ^2.0.1
  built_value_generator: ^8.1.1
  built_value: ^8.1.2
  analyzer: ">=4.2.0 <8.0.0"
dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.2
  build_test: ^2.0.0
  pedantic: ^1.11.0
