name: ferry_generator
version: 0.8.2-dev.2
homepage: https://ferrygraphql.com/
description: Generated types for Ferry GraphQL Client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'
topics:
  - graphql
  - gql
  - ferry
  - codegen
dependencies:
  gql: '>=0.14.0 <2.0.0'
  gql_code_builder: ^0.9.1+1
  gql_tristate_value: ^1.0.0
  built_collection: ^5.0.0
  code_builder: ^4.3.0
  build: ^2.0.0
  path: ^1.8.0
  ferry_exec: ^0.5.0-dev.0+1
  yaml: ^3.1.0
  dart_style: ^2.3.2
  glob: ^2.0.1
  built_value_generator: ^8.1.1
  built_value: ^8.1.2
  analyzer: ">=4.2.0 <6.0.0"
dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.2
  build_test: ^2.0.0
  pedantic: ^1.11.0
