name: ferry_generator
version: 0.5.0-dev.9
homepage: https://ferrygraphql.com/
description: Generated types for Ferry GraphQL Client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql: ^0.13.0
  gql_code_builder: ^0.5.0
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  build: ^2.0.0
  path: ^1.8.0
  ferry_exec: ^0.1.5-dev.1
  yaml: ^3.1.0
  dart_style: ^2.0.3
  glob: ^2.0.1
  built_value_generator: ^8.1.1
  built_value: ^8.1.2
dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.2
  build_test: ^2.0.0
  pedantic: ^1.11.0
