name: ferry_offline_client
version: 0.0.1
homepage: https://ferrygraphql.com/
description: An offline-ready Ferry GraphQL Client
repository: https://github.com/gql-dart/ferry
environment: 
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  gql_link: ^0.3.0
  meta: ^1.1.8
  hive: ^1.4.4
  hive_flutter: ^0.3.0+2
  ferry_exec: ^0.0.2
  ferry_cache: ^0.4.2
  ferry_hive_store: ^0.3.2
  retry: 3.0.1
  ferry: ^0.9.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  test: ^1.9.4
  pedantic: ^1.9.0
  ferry_test_graphql: ^0.0.2
