name: ferry_cache
version: 0.8.0-dev.2
homepage: https://ferrygraphql.com/
description: A normalized, strongly typed, optimistic cache for GraphQL Operations and Fragments
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'
topics:
  - graphql
  - gql
  - ferry
dependencies:
  ferry_exec: ^0.6.0
  meta: ^1.3.0
  rxdart: ^0.27.1
  normalize: ^0.9.1-dev.0
  ferry_store: ^0.5.3-dev.0+1
  collection: ^1.15.0
  pedantic: ^1.11.0
dev_dependencies:
  test: ^1.16.8
  ferry_test_graphql2: ^0.3.0
  gql_exec: ^1.0.0
  gql: ^1.0.0
  gql_tristate_value: ^1.0.0