name: ferry_cache
version: 0.7.1-dev.5
homepage: https://ferrygraphql.com/
description: A normalized, strongly typed, optimistic cache for GraphQL Operations and Fragments
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ferry_exec: ^0.3.0-dev.4
  meta: ^1.3.0
  rxdart: ^0.27.1
  normalize: ^0.8.0-dev.5
  ferry_store: ^0.5.1-dev.4
  collection: ^1.15.0
  pedantic: ^1.11.0
dev_dependencies:
  test: ^1.16.8
  ferry_test_graphql2: ^0.2.1-dev.3