name: ferry_hive_store
version: 0.4.0-1.0.nullsafety.0
homepage: https://ferrygraphql.com/
description: Hive-based Store implementation for Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  hive: ^2.0.0
  ferry_store: ">=0.4.0-1.0.nullsafety.0 <0.4.0-2.0.nullsafety.0"
  rxdart: ^0.26.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
