name: normalize
version: 0.5.5-dev.6
homepage: https://github.com/gql-dart/ferry/tree/master/normalize
description: Normalization and denormalization of GraphQL responses in Dart
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql: ^0.13.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
