name: normalize
version: 0.5.3
homepage: https://github.com/gql-dart/ferry/tree/master/normalize
description: Normalization and denormalization of GraphQL responses in Dart
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'
dependencies:
  gql: ^0.13.0-nullsafety.1
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0
