name: normalize
version: 0.4.6
homepage: https://github.com/gql-dart/ferry/tree/master/normalize
description: Normalization and denormalization of GraphQL responses in Dart
repository: https://github.com/gql-dart/ferry
environment: 
  sdk: '>=2.2.2 <3.0.0'
dependencies: 
  gql: ^0.12.4
  meta: ^1.1.8
dev_dependencies: 
  test: ^1.14.3
  pedantic: ^1.9.0
