name: ferry_flutter
version: 0.3.2
homepage: https://ferrygraphql.com/
description: Flutter widgets for the Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  ferry: ^0.9.2
  gql_exec: ^0.2.4
  ferry_exec: ^0.0.2
  flutter: 
    sdk: flutter
  flutter_test: 
    sdk: flutter
dev_dependencies: 
  test: ^1.9.4
  mockito: ^4.1.1
  pedantic: ^1.9.0
