name: ferry_flutter
version: 0.5.1-0.0.nullsafety.0
homepage: https://ferrygraphql.com/
description: Flutter widgets for the Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ferry: ^0.10.0-nullsafety.0
  gql_exec: ^0.3.0-nullsafety.2
  ferry_exec: '>=0.1.1-1.1.nullsafety.0 <0.1.1-2.0.nullsafety.0'
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
dev_dependencies:
  test: ^1.16.5
  mockito: ^5.0.2
  pedantic: ^1.11.0
