name: ferry_generator
version: 0.2.0
homepage: https://github.com/gql-dart/ferry/tree/master/ferry_generator
description: Generated types for Ferry GraphQL Client
repository: https://github.com/gql-dart/ferry
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  gql: ^0.12.0
  gql_build: ^0.1.1
  gql_code_builder: ^0.1.1
  built_collection: ^4.3.2
  code_builder: ^3.2.1
  build: ^1.2.2
  uuid: ^2.2.0
  path: ^1.7.0
dev_dependencies: 
  test: ^1.9.4
  build_runner: ^1.10.1
  build_test: ^0.10.12+1
