name: ferry_cache
version: 0.4.1
homepage: https://ferrygraphql.com/
description: A normalized, strongly typed, optimistic cache for GraphQL Operations and Fragments
repository: https://github.com/gql-dart/ferry
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  ferry_exec: ^0.0.1
  meta: ^1.1.8
  rxdart: ^0.25.0-beta3
  normalize: ^0.4.3
  ferry_store: ^0.3.1
  collection: ^1.14.13
dev_dependencies: 
  test: ^1.9.4
  pedantic: ^1.9.0
  ferry_test_graphql: ^0.0.1+2
