name: ferry_test_graphql2
version: 0.3.0-dev.3
description: Example GraphQL Operations, used in Ferry tests
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.0.0
  gql: '>=0.14.0 <2.0.0'
  gql_exec: '>=0.4.0 <2.0.0'
  gql_link: '>=0.5.0 <2.0.0'
  ferry_exec: ^0.6.1-dev.1
  built_value: ^8.0.4
  built_collection: ^5.0.0
  gql_code_builder_serializers: ^0.1.0
dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.2
  pedantic: ^1.11.0
  built_value_generator: ^8.1.1
  dart_style: ^2.3.2
  ferry_generator: ^0.12.0


