name: ferry_test_graphql2
version: 0.2.1-dev.1
description: Example GraphQL Operations, used in Ferry tests
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ferry_exec: ^0.3.0-dev.0+1
  built_value: ^8.0.4
  built_collection: ^5.0.0
  gql_code_builder: ^0.7.0
dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.2
  pedantic: ^1.11.0
  ferry_generator: ^0.8.0-dev.2
  built_value_generator: ^8.1.1
