name: ferry_flutter
version: 0.6.1
homepage: https://ferrygraphql.com/
description: Flutter widgets for the Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ferry: ^0.10.2
  gql_exec: ^0.4.0
  ferry_exec: ^0.1.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
dev_dependencies:
  test: ^1.16.5
  mockito: ^5.0.2
  pedantic: ^1.11.0
