name: ferry_exec
version: 0.1.4-dev.4
homepage: https://ferrygraphql.com/
description: A strongly typed execution interface for GraphQL operations
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  meta: ^1.3.0
  async: ^2.5.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
  ferry_test_graphql: ^0.1.4-dev.4