name: ferry
version: 0.16.1-dev.0+2
homepage: https://ferry.gql-dart.dev
description: Ferry is a simple, powerful GraphQL Client for Flutter and Dart.
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - graphql
  - gql
  - ferry
dependencies:
  gql: '>=0.14.0 <2.0.0'
  rxdart: ^0.28.0
  gql_link: '>=0.5.0 <2.0.0'
  gql_exec: '>=0.4.0 <2.0.0'
  meta: ^1.3.0
  collection: ^1.15.0
  hive: ^2.0.0
  built_value: ^8.0.4
  ferry_exec: ^0.7.0-dev.0
  normalize: ^0.10.0
  ferry_cache: ^0.10.0
dev_dependencies:
  test: ^1.16.8
  mockito: ^5.3.1
  build_test: ^2.0.0
  built_value_generator: ^8.0.4
  ferry_test_graphql2: ^0.4.0-dev.0
  pedantic: ^1.11.0
  async: ^2.5.0
  build_runner: ^2.0.2
  benchmarking: ^0.6.1
