name: ferry
version: 0.10.4-dev.7
homepage: https://ferrygraphql.com/
description: Ferry is a simple, powerful GraphQL Client for Flutter and Dart.
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql: ^0.13.0
  rxdart: ^0.27.1
  gql_link: ^0.4.0
  gql_exec: ^0.3.0
  meta: ^1.3.0
  collection: ^1.15.0
  hive: ^2.0.0
  built_value: ^8.0.4
  ferry_exec: ^0.1.4-dev.7
  normalize: ^0.5.5-dev.7
  ferry_cache: ^0.5.5-dev.7
dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.2
  build_test: ^2.0.0
  built_value_generator: ^8.0.4
  ferry_test_graphql: ^0.1.4-dev.7
  pedantic: ^1.11.0
  async: ^2.5.0
  build_runner: ^2.0.2
  benchmarking: ^0.6.1
