name: ferry_store
version: 0.4.1-0.0.nullsafety.0
homepage: https://ferrygraphql.com/
description: Default Store for Ferry GraphQL client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  rxdart: ^0.26.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
